version: '3'
services:
  server:
    image: node:14
    ports:
      - 3000:3000
    container_name: my-app_server
    depends_on:
      - mongo
    environment:
      - JWT_KEY=secret
      - CONNECTION_STRING=mongodb://mongo/my-app
    volumes:
      - ./:/app
    command: >
      sh -c "cd /app && rm -rf node_modules/ && npm i && npm run dev"
      
  mongo:
    image: mongo
    ports:
      - 27017:27017
    container_name: my-app_mongo